# NusaShop Configuration

# Pengaturan GUI
gui:
  main-title: "&8⚒ &bNusaTown &7Shop"
  category-title: "&8⚒ &b%category% &7Shop"
  
# Pengaturan ekonomi
economy:
  # Format mata uang (mengganti %amount%)
  format: "&e%amount% Coins"
  
# Pengaturan shop
shop:
  # Apakah mengijinkan pembelian tanpa konfirmasi
  buy-without-confirm: false
  
  # Apakah mengijinkan penjualan tanpa konfirmasi
  sell-without-confirm: false
  
  # Suara saat berhasil melakukan transaksi
  success-sound: ENTITY_PLAYER_LEVELUP
  
  # Suara saat gagal melakukan transaksi
  fail-sound: ENTITY_VILLAGER_NO

# Konfigurasi Event Spesial
events:
  enabled: true
  # Format waktu: yyyy-MM-dd HH:mm:ss
  current-event:
    name: "&c&lFestival Panen"
    description: "&eHarga jual item pertanian meningkat 50%!"
    start-time: "2025-04-01 00:00:00"
    end-time: "2025-04-07 23:59:59"
    sell-multiplier: 1.0  # Ubah menjadi 1.0 agar tidak ada bonus global
    announcement-interval: 30
    # Kategori dengan multiplier khusus
    category-multipliers:
      farming: 1.5    # +50% untuk kategori farming saja
    # Item dengan multiplier khusus (opsional)
    item-multipliers:
      diamond: 1.75   # Tetap +75% untuk diamond 
      gold_ingot: 1.6 # Tetap +60% untuk gold_ingot
  
  # Jadwal event yang akan datang (event akan otomatis aktif sesuai jadwal)
  upcoming-events:
    - name: "&b&lFestival Tambang"
      description: "&eHarga jual item tambang meningkat 40%!"
      start-time: "2025-05-01 00:00:00"
      end-time: "2025-05-07 23:59:59"
      sell-multiplier: 1.2
      category-multipliers:
        mining: 1.4
    
    - name: "&d&lHari Diskon"
      description: "&eHarga beli semua item menurun 15%!"
      start-time: "2025-06-01 00:00:00"
      end-time: "2025-06-03 23:59:59"
      buy-multiplier: 0.85